---
title: "Aggressiveness"
author: "Andrew Lim"
date: '2017-07-08'
output: pdf_document
---

```{r}
suppressMessages(library(tidyverse))
```

```{r}
data <- suppressMessages(read_csv("../data/AllActionsperMatchUSAMajorLeagueSoccer2016.csv"))
match_data <- suppressMessages(read_csv("../data/TeamDataMLS2016.csv"))

match_data <- match_data %>%
  rename(match_result = Result)
```

```{r}
# Joining the two tables:
data <- data %>% 
  left_join(match_data, by=c("Match" = "Matchid", `Team in possession` = "Team"))
```


```{r}
aggressive_df <- data %>% 
  mutate(next_team = lead(team)) %>% 
  mutate(turn_over = team != next_team) %>% 
  mutate(aggressive_turnover = LocX > 50 & turn_over == TRUE) %>% 
  mutate(aggressive_turnover_by_team = aggressive_turnover == TRUE & `Team in possession` == next_team) %>% 
  select(`Team in possession`, next_team, aggressive_turnover, aggressive_turnover_by_team, everything()) %>%
  group_by(Match, `Team in possession`) %>% 
  summarize(num_aggressive_turnovers = sum(aggressive_turnover),
            match_result = unique(match_result),
            HomeAway = unique(HomeAway)) %>% 
  mutate(is_home = ifelse(HomeAway == "T", TRUE, FALSE)) %>% 
  mutate(is_win = match_result == "W")

aggressive_df
```

```{r}
# The following code was obtained from: https://sebastiansauer.github.io/convert_logit2prob/
logit2prob <- function(logit){
  odds <- exp(logit)
  prob <- odds / (1 + odds)
  return(prob)
}
```

```{r}
# Teams tend to play more aggressive when they are at home:
model <- lm(num_aggressive_turnovers ~ is_home, data=aggressive_df)
summary(model)
```

```{r}
# Teams should be more aggressive when they are away in order to best improve their chances of winning:
model2 <- glm(is_win ~ num_aggressive_turnovers + is_home + is_home*num_aggressive_turnovers, data=aggressive_df)
summary(model2)
```

$$P(win) = \frac{1}{1 + e^{-x}}$$
Where: 

$$x = 0.65 - 0.0036 * (\text{number of aggressive turnovers) + 0.883 * (is at home) - 0.033 * (number of aggressive turnovers * is at home) }$$


```{r}
1/(1 + exp(-0.65))
```

The above is the chances of winning under the following conditions:
  * Away
  * Zero aggressive turn overs
  
  
```{r}
1/(1+exp(-(0.65 + 0.883)))
```

The above is the chances of winning under the following conditions:
  * Home
  * Zero aggressive turn overs


