---
title: "Exploratory Data Analysis"
author: "Andrew Lim"
date: '2017-07-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(viridis)
```

```{r}
data <- read_csv("../data/AllActionsperMatchUSAMajorLeagueSoccer2016.csv")
head(data)
```

```{r}
tst <- data %>% 
  mutate(goal_bool = Action == "goal attempt" & Result == "Goal") %>%
  group_by(team) %>% 
  mutate(lag1 = lag(Action, 1),
         lag2 = lag(Action, 2),
         lag3 = lag(Action, 3),
         lag4 = lag(Action, 4),
         lag5 = lag(Action, 5)) %>% 
  filter(goal_bool == TRUE) 

ggplot(tst, aes(lag1, fill=team)) + 
  geom_histogram(stat="count") + 
  coord_flip() + 
  scale_fill_viridis(discrete=TRUE)
```

```{r}
passes <- data %>% 
  filter(Action == "pass") 

# 10 15 25
ggplot(passes, aes(distance)) + 
  geom_histogram()
```

```{r}
data %>% 
  mutate(goal_bool = Action == "goal attempt" & Result == "Goal") %>%
  group_by(team) %>% 
  mutate(lag1 = lag(Action, 1),
         lag1_distance = lag(distance),
         lag2 = lag(Action, 2),
         lag3 = lag(Action, 3),
         lag4 = lag(Action, 4),
         lag5 = lag(Action, 5)) %>% 
  filter(goal_bool == TRUE) %>% 
  mutate(is_pass = lag1 == "pass") %>% 
  filter
```






